### ISSUE TITLE
ynt不能被解压

### ISSUE THREAD

**Issue by 418704194** [elitezhe/ynotebackparsing#1]
win7 x64位的有道云笔记的V5.7.0.0 导出的ynt，不能被Bandizip/WinRAR 解压？请问如何处理啊？

**Comment by elitezhe** [comment]
@418704194  和系统应该没有关系. 我用的360压缩 你可以下一个试试

**Comment by 418704194** [comment]
是的，换用好压解压成功，多谢！

**Comment by happyjanezj** [comment]
360解压ok
